// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoundStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  gameDefinitionId: __t.u64().name("game_definition_id"),
  currentMultiplier: __t.option(__t.f64()).name("current_multiplier"),
  crashMultiplier: __t.option(__t.f64()).name("crash_multiplier"),
  get status() {
    return RoundStatus;
  },
  countdownStartTime: __t.timestamp().name("countdown_start_time"),
  targetStartTime: __t.timestamp().name("target_start_time"),
  countdownSecondsRemaining: __t.i32().name("countdown_seconds_remaining"),
  startTime: __t.option(__t.timestamp()).name("start_time"),
  crashTime: __t.option(__t.timestamp()).name("crash_time"),
});
