// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  margin: __t.f64(),
  tickMilliseconds: __t.u32().name("tick_milliseconds"),
  maxMultiplier: __t.f64().name("max_multiplier"),
  countdownSeconds: __t.i32().name("countdown_seconds"),
  cooldownSeconds: __t.i32().name("cooldown_seconds"),
});
