// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveRound = __t.object("ActiveRound", {
  id: __t.u64(),
  gameDefinitionId: __t.u64(),
  currentMultiplier: __t.option(__t.f64()),
  crashMultiplier: __t.option(__t.f64()),
  get status() {
    return RoundStatus;
  },
  countdownStartTime: __t.timestamp(),
  targetStartTime: __t.timestamp(),
  countdownSecondsRemaining: __t.i32(),
  startTime: __t.option(__t.timestamp()),
  crashTime: __t.option(__t.timestamp()),
});
export type ActiveRound = __Infer<typeof ActiveRound>;

export const Bet = __t.object("Bet", {
  id: __t.u64(),
  roundId: __t.u64(),
  player: __t.identity(),
  amount: __t.f64(),
  cashoutMultiplier: __t.option(__t.f64()),
});
export type Bet = __Infer<typeof Bet>;

export const CompletedRound = __t.object("CompletedRound", {
  id: __t.u64(),
  gameDefinitionId: __t.u64(),
  crashMultiplier: __t.f64(),
  countdownStartTime: __t.timestamp(),
  targetStartTime: __t.timestamp(),
  startTime: __t.timestamp(),
  crashTime: __t.timestamp(),
});
export type CompletedRound = __Infer<typeof CompletedRound>;

export const GameDefinition = __t.object("GameDefinition", {
  id: __t.u64(),
  name: __t.string(),
  margin: __t.f64(),
  tickMilliseconds: __t.u32(),
  maxMultiplier: __t.f64(),
  countdownSeconds: __t.i32(),
  cooldownSeconds: __t.i32(),
});
export type GameDefinition = __Infer<typeof GameDefinition>;

export const PrivateActiveRound = __t.object("PrivateActiveRound", {
  id: __t.u64(),
  crashMultiplier: __t.f64(),
});
export type PrivateActiveRound = __Infer<typeof PrivateActiveRound>;

// The tagged union or sum type for the algebraic type `RoundStatus`.
export const RoundStatus = __t.enum("RoundStatus", {
  Countdown: __t.unit(),
  InProgress: __t.unit(),
  Ended: __t.unit(),
  Complete: __t.unit(),
});
export type RoundStatus = __Infer<typeof RoundStatus>;

export const TickSchedule = __t.object("TickSchedule", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameDefinitionId: __t.u64(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

